-- Secuencia
CREATE SEQUENCE PETS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Tabla
CREATE TABLE PETS (
  ID          NUMBER(19) PRIMARY KEY,
  NAME        VARCHAR2(200) NOT NULL,
  SPECIES     VARCHAR2(100),
  BREED       VARCHAR2(100),
  AGE         NUMBER(5),
  PRICE       NUMBER(18,2),
  DESCRIPTION VARCHAR2(2000),
  BIRTH_DATE  DATE,
  IMAGE_URL   VARCHAR2(1000)
);

COMMIT;
-- (Opcional) permisos:
-- GRANT SELECT, INSERT, UPDATE, DELETE ON PETS TO TU_USUARIO;

ALTER TABLE pets MODIFY (price FLOAT(53));

COMMIT;